// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: proto/moderation_service/moderation_service.proto

package moderation_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentifyAndReplaceTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IdentifyAndReplaceTextRequest) Reset() {
	*x = IdentifyAndReplaceTextRequest{}
	mi := &file_proto_moderation_service_moderation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyAndReplaceTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyAndReplaceTextRequest) ProtoMessage() {}

func (x *IdentifyAndReplaceTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moderation_service_moderation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyAndReplaceTextRequest.ProtoReflect.Descriptor instead.
func (*IdentifyAndReplaceTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_moderation_service_moderation_service_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyAndReplaceTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IdentifyAndReplaceTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnedContent string `protobuf:"bytes,1,opt,name=ReturnedContent,proto3" json:"ReturnedContent,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *IdentifyAndReplaceTextResponse) Reset() {
	*x = IdentifyAndReplaceTextResponse{}
	mi := &file_proto_moderation_service_moderation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyAndReplaceTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyAndReplaceTextResponse) ProtoMessage() {}

func (x *IdentifyAndReplaceTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moderation_service_moderation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyAndReplaceTextResponse.ProtoReflect.Descriptor instead.
func (*IdentifyAndReplaceTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_moderation_service_moderation_service_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyAndReplaceTextResponse) GetReturnedContent() string {
	if x != nil {
		return x.ReturnedContent
	}
	return ""
}

func (x *IdentifyAndReplaceTextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_moderation_service_moderation_service_proto protoreflect.FileDescriptor

var file_proto_moderation_service_moderation_service_proto_rawDesc = []byte{
	0x0a, 0x31, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x39, 0x0a, 0x1d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x41, 0x6e, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x1e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x84, 0x01, 0x0a,
	0x11, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6f, 0x0a, 0x16, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x41, 0x6e,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x29, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x79, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x41, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_moderation_service_moderation_service_proto_rawDescOnce sync.Once
	file_proto_moderation_service_moderation_service_proto_rawDescData = file_proto_moderation_service_moderation_service_proto_rawDesc
)

func file_proto_moderation_service_moderation_service_proto_rawDescGZIP() []byte {
	file_proto_moderation_service_moderation_service_proto_rawDescOnce.Do(func() {
		file_proto_moderation_service_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_moderation_service_moderation_service_proto_rawDescData)
	})
	return file_proto_moderation_service_moderation_service_proto_rawDescData
}

var file_proto_moderation_service_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_moderation_service_moderation_service_proto_goTypes = []any{
	(*IdentifyAndReplaceTextRequest)(nil),  // 0: moderation.IdentifyAndReplaceTextRequest
	(*IdentifyAndReplaceTextResponse)(nil), // 1: moderation.IdentifyAndReplaceTextResponse
}
var file_proto_moderation_service_moderation_service_proto_depIdxs = []int32{
	0, // 0: moderation.ModerationService.IdentifyAndReplaceText:input_type -> moderation.IdentifyAndReplaceTextRequest
	1, // 1: moderation.ModerationService.IdentifyAndReplaceText:output_type -> moderation.IdentifyAndReplaceTextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_moderation_service_moderation_service_proto_init() }
func file_proto_moderation_service_moderation_service_proto_init() {
	if File_proto_moderation_service_moderation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_moderation_service_moderation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_moderation_service_moderation_service_proto_goTypes,
		DependencyIndexes: file_proto_moderation_service_moderation_service_proto_depIdxs,
		MessageInfos:      file_proto_moderation_service_moderation_service_proto_msgTypes,
	}.Build()
	File_proto_moderation_service_moderation_service_proto = out.File
	file_proto_moderation_service_moderation_service_proto_rawDesc = nil
	file_proto_moderation_service_moderation_service_proto_goTypes = nil
	file_proto_moderation_service_moderation_service_proto_depIdxs = nil
}
