// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: proto/otp_service/otp_service.proto

package otp_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendForgetPasswordOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *SendForgetPasswordOTPRequest) Reset() {
	*x = SendForgetPasswordOTPRequest{}
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendForgetPasswordOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendForgetPasswordOTPRequest) ProtoMessage() {}

func (x *SendForgetPasswordOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendForgetPasswordOTPRequest.ProtoReflect.Descriptor instead.
func (*SendForgetPasswordOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_service_otp_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendForgetPasswordOTPRequest) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *SendForgetPasswordOTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendForgetPasswordOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *SendForgetPasswordOTPResponse) Reset() {
	*x = SendForgetPasswordOTPResponse{}
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendForgetPasswordOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendForgetPasswordOTPResponse) ProtoMessage() {}

func (x *SendForgetPasswordOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendForgetPasswordOTPResponse.ProtoReflect.Descriptor instead.
func (*SendForgetPasswordOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_service_otp_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendForgetPasswordOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckValidOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	OTP       uint64 `protobuf:"varint,2,opt,name=OTP,proto3" json:"OTP,omitempty"`
}

func (x *CheckValidOTPRequest) Reset() {
	*x = CheckValidOTPRequest{}
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckValidOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckValidOTPRequest) ProtoMessage() {}

func (x *CheckValidOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckValidOTPRequest.ProtoReflect.Descriptor instead.
func (*CheckValidOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_service_otp_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckValidOTPRequest) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *CheckValidOTPRequest) GetOTP() uint64 {
	if x != nil {
		return x.OTP
	}
	return 0
}

type CheckValidOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid  bool   `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	Attempts uint32 `protobuf:"varint,2,opt,name=Attempts,proto3" json:"Attempts,omitempty"`
}

func (x *CheckValidOTPResponse) Reset() {
	*x = CheckValidOTPResponse{}
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckValidOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckValidOTPResponse) ProtoMessage() {}

func (x *CheckValidOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_service_otp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckValidOTPResponse.ProtoReflect.Descriptor instead.
func (*CheckValidOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_service_otp_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckValidOTPResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *CheckValidOTPResponse) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

var File_proto_otp_service_otp_service_proto protoreflect.FileDescriptor

var file_proto_otp_service_otp_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x74, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x6f, 0x74, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x52, 0x0a, 0x1c, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x39,
	0x0a, 0x1d, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x4f, 0x54, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x4f, 0x54,
	0x50, 0x22, 0x4d, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4f,
	0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73,
	0x32, 0xb4, 0x01, 0x0a, 0x0a, 0x4f, 0x54, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5e, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x4f, 0x54, 0x50, 0x12, 0x21, 0x2e, 0x6f, 0x74, 0x70, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x74,
	0x70, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x46, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4f, 0x54, 0x50,
	0x12, 0x19, 0x2e, 0x6f, 0x74, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6f, 0x74,
	0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4f, 0x54, 0x50, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6f, 0x74, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_otp_service_otp_service_proto_rawDescOnce sync.Once
	file_proto_otp_service_otp_service_proto_rawDescData = file_proto_otp_service_otp_service_proto_rawDesc
)

func file_proto_otp_service_otp_service_proto_rawDescGZIP() []byte {
	file_proto_otp_service_otp_service_proto_rawDescOnce.Do(func() {
		file_proto_otp_service_otp_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_otp_service_otp_service_proto_rawDescData)
	})
	return file_proto_otp_service_otp_service_proto_rawDescData
}

var file_proto_otp_service_otp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_otp_service_otp_service_proto_goTypes = []any{
	(*SendForgetPasswordOTPRequest)(nil),  // 0: otp.SendForgetPasswordOTPRequest
	(*SendForgetPasswordOTPResponse)(nil), // 1: otp.SendForgetPasswordOTPResponse
	(*CheckValidOTPRequest)(nil),          // 2: otp.CheckValidOTPRequest
	(*CheckValidOTPResponse)(nil),         // 3: otp.CheckValidOTPResponse
}
var file_proto_otp_service_otp_service_proto_depIdxs = []int32{
	0, // 0: otp.OTPService.SendForgetPasswordOTP:input_type -> otp.SendForgetPasswordOTPRequest
	2, // 1: otp.OTPService.CheckValidOTP:input_type -> otp.CheckValidOTPRequest
	1, // 2: otp.OTPService.SendForgetPasswordOTP:output_type -> otp.SendForgetPasswordOTPResponse
	3, // 3: otp.OTPService.CheckValidOTP:output_type -> otp.CheckValidOTPResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_otp_service_otp_service_proto_init() }
func file_proto_otp_service_otp_service_proto_init() {
	if File_proto_otp_service_otp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_otp_service_otp_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_otp_service_otp_service_proto_goTypes,
		DependencyIndexes: file_proto_otp_service_otp_service_proto_depIdxs,
		MessageInfos:      file_proto_otp_service_otp_service_proto_msgTypes,
	}.Build()
	File_proto_otp_service_otp_service_proto = out.File
	file_proto_otp_service_otp_service_proto_rawDesc = nil
	file_proto_otp_service_otp_service_proto_goTypes = nil
	file_proto_otp_service_otp_service_proto_depIdxs = nil
}
