// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: proto/privacy_service/privacy_service.proto

package privacy_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountPrivacyInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID string `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
}

func (x *CreateAccountPrivacyInitRequest) Reset() {
	*x = CreateAccountPrivacyInitRequest{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountPrivacyInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountPrivacyInitRequest) ProtoMessage() {}

func (x *CreateAccountPrivacyInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountPrivacyInitRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountPrivacyInitRequest) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountPrivacyInitRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

type CreateAccountPrivacyInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateAccountPrivacyInitResponse) Reset() {
	*x = CreateAccountPrivacyInitResponse{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountPrivacyInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountPrivacyInitResponse) ProtoMessage() {}

func (x *CreateAccountPrivacyInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountPrivacyInitResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountPrivacyInitResponse) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountPrivacyInitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountPrivacyInitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPrivacyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
}

func (x *GetPrivacyRequest) Reset() {
	*x = GetPrivacyRequest{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacyRequest) ProtoMessage() {}

func (x *GetPrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacyRequest.ProtoReflect.Descriptor instead.
func (*GetPrivacyRequest) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPrivacyRequest) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

type GetPrivacyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Privacy *PrivacyIndices `protobuf:"bytes,1,opt,name=Privacy,proto3" json:"Privacy,omitempty"`
}

func (x *GetPrivacyResponse) Reset() {
	*x = GetPrivacyResponse{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacyResponse) ProtoMessage() {}

func (x *GetPrivacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacyResponse.ProtoReflect.Descriptor instead.
func (*GetPrivacyResponse) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPrivacyResponse) GetPrivacy() *PrivacyIndices {
	if x != nil {
		return x.Privacy
	}
	return nil
}

type PrivacyIndices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateOfBirth    string `protobuf:"bytes,1,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	Gender         string `protobuf:"bytes,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	MaterialStatus string `protobuf:"bytes,3,opt,name=MaterialStatus,proto3" json:"MaterialStatus,omitempty"`
	Phone          string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email          string `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Bio            string `protobuf:"bytes,6,opt,name=Bio,proto3" json:"Bio,omitempty"`
}

func (x *PrivacyIndices) Reset() {
	*x = PrivacyIndices{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyIndices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyIndices) ProtoMessage() {}

func (x *PrivacyIndices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyIndices.ProtoReflect.Descriptor instead.
func (*PrivacyIndices) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{4}
}

func (x *PrivacyIndices) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *PrivacyIndices) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PrivacyIndices) GetMaterialStatus() string {
	if x != nil {
		return x.MaterialStatus
	}
	return ""
}

func (x *PrivacyIndices) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PrivacyIndices) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PrivacyIndices) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type SetPrivacyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID     uint64 `protobuf:"varint,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	PrivacyIndex  uint32 `protobuf:"varint,2,opt,name=PrivacyIndex,proto3" json:"PrivacyIndex,omitempty"`
	PrivacyStatus string `protobuf:"bytes,3,opt,name=PrivacyStatus,proto3" json:"PrivacyStatus,omitempty"`
}

func (x *SetPrivacyRequest) Reset() {
	*x = SetPrivacyRequest{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrivacyRequest) ProtoMessage() {}

func (x *SetPrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrivacyRequest.ProtoReflect.Descriptor instead.
func (*SetPrivacyRequest) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetPrivacyRequest) GetAccountID() uint64 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *SetPrivacyRequest) GetPrivacyIndex() uint32 {
	if x != nil {
		return x.PrivacyIndex
	}
	return 0
}

func (x *SetPrivacyRequest) GetPrivacyStatus() string {
	if x != nil {
		return x.PrivacyStatus
	}
	return ""
}

type SetPrivacyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *SetPrivacyResponse) Reset() {
	*x = SetPrivacyResponse{}
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrivacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrivacyResponse) ProtoMessage() {}

func (x *SetPrivacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_privacy_service_privacy_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrivacyResponse.ProtoReflect.Descriptor instead.
func (*SetPrivacyResponse) Descriptor() ([]byte, []int) {
	return file_proto_privacy_service_privacy_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetPrivacyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_privacy_service_privacy_service_proto protoreflect.FileDescriptor

var file_proto_privacy_service_privacy_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x22, 0x3f, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x52, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x47,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x52, 0x07,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x22, 0xb0, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x42, 0x69, 0x6f, 0x22, 0x7b, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x22, 0x0a,
	0x0c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x8f, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x49,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x12, 0x1a, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_privacy_service_privacy_service_proto_rawDescOnce sync.Once
	file_proto_privacy_service_privacy_service_proto_rawDescData = file_proto_privacy_service_privacy_service_proto_rawDesc
)

func file_proto_privacy_service_privacy_service_proto_rawDescGZIP() []byte {
	file_proto_privacy_service_privacy_service_proto_rawDescOnce.Do(func() {
		file_proto_privacy_service_privacy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_privacy_service_privacy_service_proto_rawDescData)
	})
	return file_proto_privacy_service_privacy_service_proto_rawDescData
}

var file_proto_privacy_service_privacy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_privacy_service_privacy_service_proto_goTypes = []any{
	(*CreateAccountPrivacyInitRequest)(nil),  // 0: privacy.CreateAccountPrivacyInitRequest
	(*CreateAccountPrivacyInitResponse)(nil), // 1: privacy.CreateAccountPrivacyInitResponse
	(*GetPrivacyRequest)(nil),                // 2: privacy.GetPrivacyRequest
	(*GetPrivacyResponse)(nil),               // 3: privacy.GetPrivacyResponse
	(*PrivacyIndices)(nil),                   // 4: privacy.PrivacyIndices
	(*SetPrivacyRequest)(nil),                // 5: privacy.SetPrivacyRequest
	(*SetPrivacyResponse)(nil),               // 6: privacy.SetPrivacyResponse
}
var file_proto_privacy_service_privacy_service_proto_depIdxs = []int32{
	4, // 0: privacy.GetPrivacyResponse.Privacy:type_name -> privacy.PrivacyIndices
	0, // 1: privacy.PrivacyService.CreateAccountPrivacyInit:input_type -> privacy.CreateAccountPrivacyInitRequest
	2, // 2: privacy.PrivacyService.GetPrivacy:input_type -> privacy.GetPrivacyRequest
	5, // 3: privacy.PrivacyService.SetPrivacy:input_type -> privacy.SetPrivacyRequest
	1, // 4: privacy.PrivacyService.CreateAccountPrivacyInit:output_type -> privacy.CreateAccountPrivacyInitResponse
	3, // 5: privacy.PrivacyService.GetPrivacy:output_type -> privacy.GetPrivacyResponse
	6, // 6: privacy.PrivacyService.SetPrivacy:output_type -> privacy.SetPrivacyResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_privacy_service_privacy_service_proto_init() }
func file_proto_privacy_service_privacy_service_proto_init() {
	if File_proto_privacy_service_privacy_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_privacy_service_privacy_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_privacy_service_privacy_service_proto_goTypes,
		DependencyIndexes: file_proto_privacy_service_privacy_service_proto_depIdxs,
		MessageInfos:      file_proto_privacy_service_privacy_service_proto_msgTypes,
	}.Build()
	File_proto_privacy_service_privacy_service_proto = out.File
	file_proto_privacy_service_privacy_service_proto_rawDesc = nil
	file_proto_privacy_service_privacy_service_proto_goTypes = nil
	file_proto_privacy_service_privacy_service_proto_depIdxs = nil
}
