// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: proto/privacy_service/privacy_service.proto

package privacy_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivacyService_CreateAccountPrivacyInit_FullMethodName = "/privacy.PrivacyService/CreateAccountPrivacyInit"
)

// PrivacyServiceClient is the client API for PrivacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivacyServiceClient interface {
	CreateAccountPrivacyInit(ctx context.Context, in *CreateAccountPrivacyInitRequest, opts ...grpc.CallOption) (*CreateAccountPrivacyInitResponse, error)
}

type privacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivacyServiceClient(cc grpc.ClientConnInterface) PrivacyServiceClient {
	return &privacyServiceClient{cc}
}

func (c *privacyServiceClient) CreateAccountPrivacyInit(ctx context.Context, in *CreateAccountPrivacyInitRequest, opts ...grpc.CallOption) (*CreateAccountPrivacyInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountPrivacyInitResponse)
	err := c.cc.Invoke(ctx, PrivacyService_CreateAccountPrivacyInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivacyServiceServer is the server API for PrivacyService service.
// All implementations must embed UnimplementedPrivacyServiceServer
// for forward compatibility.
type PrivacyServiceServer interface {
	CreateAccountPrivacyInit(context.Context, *CreateAccountPrivacyInitRequest) (*CreateAccountPrivacyInitResponse, error)
	mustEmbedUnimplementedPrivacyServiceServer()
}

// UnimplementedPrivacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivacyServiceServer struct{}

func (UnimplementedPrivacyServiceServer) CreateAccountPrivacyInit(context.Context, *CreateAccountPrivacyInitRequest) (*CreateAccountPrivacyInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountPrivacyInit not implemented")
}
func (UnimplementedPrivacyServiceServer) mustEmbedUnimplementedPrivacyServiceServer() {}
func (UnimplementedPrivacyServiceServer) testEmbeddedByValue()                        {}

// UnsafePrivacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivacyServiceServer will
// result in compilation errors.
type UnsafePrivacyServiceServer interface {
	mustEmbedUnimplementedPrivacyServiceServer()
}

func RegisterPrivacyServiceServer(s grpc.ServiceRegistrar, srv PrivacyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivacyService_ServiceDesc, srv)
}

func _PrivacyService_CreateAccountPrivacyInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountPrivacyInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivacyServiceServer).CreateAccountPrivacyInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivacyService_CreateAccountPrivacyInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivacyServiceServer).CreateAccountPrivacyInit(ctx, req.(*CreateAccountPrivacyInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivacyService_ServiceDesc is the grpc.ServiceDesc for PrivacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privacy.PrivacyService",
	HandlerType: (*PrivacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountPrivacyInit",
			Handler:    _PrivacyService_CreateAccountPrivacyInit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/privacy_service/privacy_service.proto",
}
